name: Build Godot Release for PortMaster (Multi Arch)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build_portmaster:
    strategy:
      matrix:
        include:
          - arch: arm64
            runner: ubuntu-24.04-arm
            base_image: arm64v8/ubuntu:20.04
            suffix: aarch64
          - arch: x86_64
            runner: ubuntu-latest
            base_image: ubuntu:24.04
            suffix: x86_64

    runs-on: ${{ matrix.runner }}
    
    container:
      image: ${{ matrix.base_image }}
      options: --user root

    steps:
      - name: Install Git and Checkout
        run: |
          apt-get update
          apt-get install -y git
        
      - uses: actions/checkout@v5

      - name: Install PortMaster Match Dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get install -y build-essential pkg-config squashfs-tools python3-pip \
            libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libasound2-dev \
            libpulse-dev libudev-dev libxi-dev libxrandr-dev \
            libwayland-dev libxkbcommon-dev

      - name: Install SCons
        run: |
          pip3 install scons
          
      - uses: actions/cache@v5
        with:
          path: ~/.cache/scons
          key: ${{ runner.os }}-pm-scons-v4-${{ matrix.arch }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-pm-scons-v4-${{ matrix.arch }}-

      - name: Compile 3D Full
        run: |
          scons -j$(nproc) platform=linuxbsd arch=${{ matrix.arch }} target=template_release optimize=speed \
            production=yes lto=full disable_path_overrides=no use_static_cpp=yes tools=no \
            deprecated=no minizip=no module_lightmapper_rd_enabled=no

      - name: Prepare 3D Full
        run: |
          cd bin/
          strip $(ls godot.linuxbsd.template_release.${{ matrix.arch }}*)
          mv $(ls godot.linuxbsd.template_release.${{ matrix.arch }}*) godot_3d.${{ matrix.suffix }}

      - name: Compile Compat
        run: |
          scons -j$(nproc) platform=linuxbsd arch=${{ matrix.arch }} target=template_release optimize=speed \
            production=yes lto=full disable_path_overrides=no use_static_cpp=yes tools=no \
            deprecated=no minizip=no module_basis_universal_enabled=no module_gltf_enabled=no \
            module_gridmap_enabled=no module_msdfgen_enabled=no module_openxr_enabled=no \
            module_raycast_enabled=no module_lightmapper_rd_enabled=no

      - name: Prepare Compat
        run: |
          cd bin/
          strip $(ls godot.linuxbsd.template_release.${{ matrix.arch }}*)
          mv $(ls godot.linuxbsd.template_release.${{ matrix.arch }}*) godot_compat.${{ matrix.suffix }}

      - name: Compile Optimised
        run: |
          scons -j$(nproc) platform=linuxbsd arch=${{ matrix.arch }} target=template_release optimize=speed \
            production=yes lto=full disable_path_overrides=no use_static_cpp=yes tools=no \
            disable_advanced_gui=yes deprecated=no minizip=no module_basis_universal_enabled=no \
            module_gltf_enabled=no module_gridmap_enabled=no module_msdfgen_enabled=no \
            module_openxr_enabled=no module_raycast_enabled=no module_svg_enabled=no \
            module_lightmapper_rd_enabled=no module_text_server_advanced_enabled=no \
            module_text_server_fallback_enabled=yes

      - name: Prepare Optimised
        run: |
          cd bin/
          strip $(ls godot.linuxbsd.template_release.${{ matrix.arch }}*)
          mv $(ls godot.linuxbsd.template_release.${{ matrix.arch }}*) godot_optimised.${{ matrix.suffix }}

      - uses: actions/upload-artifact@v4
        with:
          name: godot_3d.${{ matrix.suffix }}
          path: bin/godot_3d.${{ matrix.suffix }}

      - uses: actions/upload-artifact@v4
        with:
          name: godot_compat.${{ matrix.suffix }}
          path: bin/godot_compat.${{ matrix.suffix }}

      - uses: actions/upload-artifact@v4
        with:
          name: godot_optimised.${{ matrix.suffix }}
          path: bin/godot_optimised.${{ matrix.suffix }}
