name: Build Godot Release for PortMaster (Native ARM64)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build_portmaster:
    runs-on: ubuntu-22.04-arm

    steps:
      - uses: actions/checkout@v5

      - run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config squashfs-tools python3-pip \
            libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libasound2-dev \
            libpulse-dev libudev-dev libxi-dev libxrandr-dev \
            libwayland-dev libwayland-bin wayland-protocols libxkbcommon-dev

      - run: |
          pip3 install --user scons
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
      - uses: actions/cache@v5
        with:
          path: ~/.cache/scons
          key: ${{ runner.os }}-scons-v1-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-scons-v1-

      - name: Compile 3D Full
        run: |
          scons -j$(nproc) platform=linuxbsd arch=arm64 target=template_release optimize=speed \
            production=yes lto=full disable_path_overrides=no use_static_cpp=yes tools=no \
            deprecated=no minizip=no module_lightmapper_rd_enabled=no

      - name: Prepare 3D Full
        run: |
          cd bin/
          strip $(ls godot.linuxbsd.template_release.arm64*)
          mv $(ls godot.linuxbsd.template_release.arm64*) godot_3d.aarch64

      - name: Compile Compat
        run: |
          scons -j$(nproc) platform=linuxbsd arch=arm64 target=template_release optimize=speed \
            production=yes lto=full disable_path_overrides=no use_static_cpp=yes tools=no \
            deprecated=no minizip=no module_basis_universal_enabled=no module_gltf_enabled=no \
            module_gridmap_enabled=no module_msdfgen_enabled=no module_openxr_enabled=no \
            module_raycast_enabled=no module_lightmapper_rd_enabled=no

      - name: Prepare Compat
        run: |
          cd bin/
          strip $(ls godot.linuxbsd.template_release.arm64*)
          mv $(ls godot.linuxbsd.template_release.arm64*) godot_compat.aarch64

      - name: Compile Optimised
        run: |
          scons -j$(nproc) platform=linuxbsd arch=arm64 target=template_release optimize=speed \
            production=yes lto=full disable_path_overrides=no use_static_cpp=yes tools=no \
            disable_advanced_gui=yes deprecated=no minizip=no module_basis_universal_enabled=no \
            module_gltf_enabled=no module_gridmap_enabled=no module_msdfgen_enabled=no \
            module_openxr_enabled=no module_raycast_enabled=no module_svg_enabled=no \
            module_lightmapper_rd_enabled=no module_text_server_advanced_enabled=no \
            module_text_server_fallback_enabled=yes

      - name: Prepare Optimised
        run: |
          cd bin/
          strip $(ls godot.linuxbsd.template_release.arm64*)
          mv $(ls godot.linuxbsd.template_release.arm64*) godot_optimised.aarch64

      - uses: actions/upload-artifact@v4
        with:
          name: godot_3d.aarch64
          path: bin/godot_3d.aarch64

      - uses: actions/upload-artifact@v4
        with:
          name: godot_compat.aarch64
          path: bin/godot_compat.aarch64

      - uses: actions/upload-artifact@v4
        with:
          name: godot_optimised.aarch64
          path: bin/godot_optimised.aarch64
